stages:
  - build
  - test
  - deploy

default:
  image: node:19.9-alpine #-alpine3.17

cache:
  - key: &global_cache_node_mods
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull
    when: on_success

install:
  stage: .pre
  cache:
    - key: ${CI_JOB_NAME}
      paths:
        - .npm/
      policy: pull-push
      when: on_success
      
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules/
      policy: pull-push
      when: on_success
  script:
    - npm ci --cache .npm --prefer-offline

build-lib:
  stage: build
  script:
    - echo "Building CEditor5 library ..."
    - npm ci
#    - npm version patch --force
    - npm run dll:build
#    - npm publish
  artifacts:
    paths:
      - "js/build/"